(()=>{const G={diabetes:['Đái tháo đường','Ưu tiên theo hạ đường huyết, tim–thận, suy yếu và khả năng tự dùng thuốc.',d=>d.domains.some(x=>x.includes('Đái tháo đường'))],cardio:['Tăng huyết áp & tim mạch','Đích huyết áp, bệnh mạch vành, suy tim và hạ huyết áp tư thế phải được nhìn cùng nhau.',d=>d.domains.some(x=>/Tăng huyết áp|Bệnh mạch vành|Suy tim|Đau thắt ngực/.test(x))],vascular:['Kháng huyết khối & lipid','Cân bằng thiếu máu cục bộ với chảy máu, đa thuốc và tương tác.',d=>/kháng|P2Y12|Statin|cholesterol/i.test(d.drug_class)||d.domains.some(x=>/ASCVD|PCI|Rối loạn lipid/.test(x))],bone:['Gout & loãng xương','Rà chức năng thận, nguy cơ gãy xương, tương tác và kế hoạch ngừng/chuyển thuốc.',d=>d.domains.some(x=>/Gout|Loãng xương/.test(x))],endocrine:['Nội tiết','Khởi liều thận trọng, theo dõi triệu chứng và xét nghiệm, tránh điều trị quá mức.',d=>d.domains.some(x=>/Suy giáp|Suy thượng thận|Cận giáp/.test(x))],gi:['Tiêu hóa','Ưu tiên nguyên nhân, dịch–điện giải và thuốc gây triệu chứng trước khi kê thêm.',d=>d.domains.some(x=>/Táo bón|Tiêu chảy/.test(x))]};let D={drugs:[]};const $=id=>document.getElementById(id),e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

const EXTRA=[
{id:'glimepiride',generic:'Glimepiride',brands:'Amaryl; generic',drug_class:'Sulfonylurea',domains:['Đái tháo đường'],route:'Uống',strengths:'Viên 1 mg, 2 mg, 4 mg',start:'Người cao tuổi/nguy cơ hạ đường huyết: 1 mg mỗi ngày cùng bữa sáng hoặc bữa chính đầu tiên.',usual:'1–4 mg/ngày, dùng 1 lần/ngày.',daily_dose:'1–4 mg/ngày thường dùng; tối đa 8 mg/ngày.',max:'8 mg/ngày.',titrate:'Tăng từng 1–2 mg, không thường xuyên hơn mỗi 1–2 tuần theo glucose/HbA1c.',duration:'Dùng 1 lần/ngày; tác dụng hạ glucose kéo dài suốt ngày trong thực hành.',prefer:'Chỉ dùng chọn lọc khi cần thuốc rẻ/hiệu lực hạ glucose và người bệnh có bữa ăn ổn định; ở lão khoa phải rất thận trọng vì hạ đường huyết.',combine:'Có thể phối hợp metformin/SGLT2i; nếu thêm insulin hoặc GLP-1 RA cần cân nhắc giảm/ngưng SU.',hold_stop:'Giảm/ngưng khi hạ đường huyết, ăn kém, sụt cân, suy thận tiến triển hoặc mục tiêu điều trị đã nới.',adverse:'Hạ đường huyết, tăng cân; hạ đường huyết có thể kéo dài ở người già/suy thận.',monitor:'Đường huyết, HbA1c, bữa ăn, cân nặng, chức năng thận và các cơn hạ đường huyết.',renal:'Khởi 1 mg và tăng chậm ở suy thận/người cao tuổi.',trend:'Không phải lựa chọn ưu tiên khi có thuốc ít gây hạ đường huyết và có lợi ích tim–thận.',exam_trap:'Người già ăn thất thường hoặc CKD mà vẫn tăng glimepiride chỉ vì HbA1c cao.'},
{id:'gliclazide-mr',generic:'Gliclazide phóng thích biến đổi (MR)',brands:'Diamicron MR; generic',drug_class:'Sulfonylurea',domains:['Đái tháo đường'],route:'Uống',strengths:'Viên MR 30 mg và 60 mg; dạng IR 80 mg còn gặp ở một số nơi.',start:'30 mg mỗi ngày, uống một lần vào bữa sáng.',usual:'30–120 mg/ngày, 1 lần vào bữa sáng.',daily_dose:'30–120 mg/ngày (MR).',max:'120 mg/ngày (MR).',titrate:'30 → 60 → 90 → 120 mg; thường cách mỗi bước ít nhất 1 tháng, có thể sớm hơn sau 2 tuần nếu glucose không giảm.',duration:'Dạng MR được thiết kế dùng 1 lần/ngày, tác dụng khoảng 24 giờ.',prefer:'Trong nhóm SU, thường được lựa chọn khi cần SU nhưng vẫn phải cân nguy cơ hạ đường huyết ở lão khoa.',combine:'Phối hợp thuốc không gây hạ đường huyết; khi phối insulin cần xem giảm SU.',hold_stop:'Giảm/ngưng khi ăn kém, hạ đường huyết, suy yếu hoặc mục tiêu điều trị nới.',adverse:'Hạ đường huyết, tăng cân; nguy cơ tăng khi bỏ bữa hoặc suy thận.',monitor:'Glucose/HbA1c, bữa ăn, hạ đường huyết, chức năng thận.',renal:'Thận trọng và cá thể hóa theo chức năng thận; tránh tăng liều máy móc ở người già.',trend:'Nếu buộc dùng SU, ưu tiên chế phẩm có nguy cơ hạ đường huyết thấp hơn các SU tác dụng kéo dài.',exam_trap:'Không phân biệt gliclazide IR 80 mg với MR 30/60 mg rồi đổi liều 1:1.'},
{id:'glipizide-ir',generic:'Glipizide phóng thích tức thì',brands:'Glucotrol; generic',drug_class:'Sulfonylurea',domains:['Đái tháo đường'],route:'Uống',strengths:'Viên 5 mg, 10 mg; một số chế phẩm có 2,5 mg.',start:'Người cao tuổi/suy yếu: 2,5 mg; thường 5 mg trước bữa sáng.',usual:'2,5–40 mg/ngày; liều >15 mg/ngày thường chia trước các bữa ăn.',daily_dose:'2,5–40 mg/ngày.',max:'40 mg/ngày; liều đơn tối đa thường 15 mg.',titrate:'Tăng 2,5–5 mg theo đáp ứng, cách nhau ít nhất vài ngày.',duration:'Khoảng 6–12 giờ với dạng IR.',prefer:'Nếu phải dùng SU ở người cao tuổi, thời gian tác dụng ngắn hơn có thể thuận lợi hơn nhưng vẫn có nguy cơ hạ đường huyết.',combine:'Có thể phối hợp thuốc khác; rà nguy cơ hạ đường huyết khi thêm insulin.',hold_stop:'Giảm/ngưng khi ăn kém, hạ đường huyết hoặc giảm cường độ điều trị.',adverse:'Hạ đường huyết, tăng cân.',monitor:'Glucose/HbA1c, bữa ăn, hạ đường huyết.',renal:'Khởi và duy trì bảo thủ ở người suy thận/gan hoặc suy dinh dưỡng.',trend:'Không ưu tiên trước SGLT2i/GLP-1 RA khi cần lợi ích tim–thận.',exam_trap:'Dùng liều như người trẻ ở bệnh nhân 80 tuổi ăn uống thất thường.'},
{id:'glipizide-er',generic:'Glipizide phóng thích kéo dài',brands:'Glucotrol XL; generic',drug_class:'Sulfonylurea',domains:['Đái tháo đường'],route:'Uống',strengths:'Viên ER 2,5 mg, 5 mg, 10 mg.',start:'5 mg mỗi ngày với bữa sáng; người cao tuổi/nguy cơ hạ đường huyết có thể khởi 2,5 mg.',usual:'2,5–20 mg/ngày, 1 lần/ngày.',daily_dose:'2,5–20 mg/ngày.',max:'20 mg/ngày.',titrate:'Điều chỉnh theo kiểm soát đường huyết và nguy cơ hạ đường huyết.',duration:'Dạng ER dùng 1 lần/ngày, tác dụng khoảng 24 giờ.',prefer:'Chọn lọc khi cần SU và phác đồ 1 lần/ngày; vẫn phải cân nguy cơ hạ đường huyết.',combine:'Phối hợp được nhưng giảm thuốc gây hạ đường huyết khi cần.',hold_stop:'Như các SU khác: giảm/ngưng khi hạ đường huyết, ăn kém, suy yếu.',adverse:'Hạ đường huyết, tăng cân.',monitor:'Glucose/HbA1c, bữa ăn, hạ đường huyết.',renal:'Khởi liều thấp hơn khi nguy cơ hạ đường huyết cao.',trend:'Ưu tiên thuốc ít hạ đường huyết hơn nếu có thể.',exam_trap:'Nhầm liều tối đa IR 40 mg với ER 20 mg.'}
];

const META=[
[/metformin/i,{strengths:'Thường gặp 500 mg, 750 mg, 850 mg, 1.000 mg tùy IR/XR và nhà sản xuất.',daily:d=>d.usual,duration:'IR thường dùng 2–3 lần/ngày; XR thường 1 lần/ngày. Thời gian tác dụng phụ thuộc chế phẩm.'}],
[/empagliflozin/i,{strengths:'Viên 10 mg, 25 mg.',daily:d=>d.usual,duration:'Dùng 1 lần/ngày; tác dụng dược lực kéo dài trong ngày.'}],
[/sitagliptin/i,{strengths:'Viên 25 mg, 50 mg, 100 mg.',daily:d=>d.usual,duration:'Dùng 1 lần/ngày.'}],
[/linagliptin/i,{strengths:'Viên 5 mg.',daily:d=>d.usual,duration:'Dùng 1 lần/ngày.'}],
[/semaglutide/i,{strengths:'Bút tiêm nhiều hàm lượng theo chế phẩm; phải đọc nhãn bút cụ thể.',daily:d=>d.usual,duration:'Dùng 1 lần mỗi tuần.'}]
];
function enrich(d){const x={...d};for(const [re,m] of META){if(re.test(x.generic||'')){x.strengths=x.strengths||m.strengths;x.daily_dose=x.daily_dose||(typeof m.daily==='function'?m.daily(x):m.daily);x.duration=x.duration||m.duration;break}}return x}
function card(d){d=enrich(d);return `<details class="drug-card-v82"><summary><div class="drug-name"><b>${e(d.generic)}</b><small>${e(d.drug_class)}</small></div><span class="dose-pill">Khởi: ${e((d.start||'').split('.')[0])}</span></summary><div class="drug-body"><div class="brandline"><span>Biệt dược ví dụ</span><b>${e(d.brands||'—')}</b><small>Chỉ để nhận diện; không hàm ý ưu tiên.</small></div>
<div class="dose-grid-v82">
<div><span>Hàm lượng / dạng bào chế</span><strong>${e(d.strengths||'Tra theo chế phẩm cụ thể')}</strong></div>
<div><span>Liều khởi trị</span><strong>${e(d.start)}</strong></div>
<div><span>Liều mỗi ngày / thường dùng</span><strong>${e(d.daily_dose||d.usual)}</strong></div>
<div><span>Liều tối đa / trần</span><strong>${e(d.max)}</strong></div>
<div><span>Cách tăng liều</span><strong>${e(d.titrate)}</strong></div>
<div><span>Thời gian tác dụng / khoảng dùng</span><strong>${e(d.duration||'Phụ thuộc chế phẩm; xem nhãn thuốc')}</strong></div>
</div>
<div class="drug-facts"><div><b>Ưu tiên</b><p>${e(d.prefer)}</p></div><div><b>Phối hợp</b><p>${e(d.combine)}</p></div><div><b>Giữ / giảm / dừng</b><p>${e(d.hold_stop)}</p></div><div><b>Tác dụng phụ</b><p>${e(d.adverse)}</p></div><div><b>Theo dõi</b><p>${e(d.monitor)}</p></div><div><b>Chức năng thận</b><p>${e(d.renal)}</p></div><div><b>Xu hướng</b><p>${e(d.trend)}</p></div></div><div class="exam"><b>Bẫy MCQ:</b> ${e(d.exam_trap)}</div></div></details>`}
function classes(a){const m={};a.forEach(d=>(m[d.drug_class]??=[]).push(d));return Object.entries(m).sort((a,b)=>a[0].localeCompare(b[0],'vi')).map(([k,v])=>`<details class="drug-class" open><summary><span>${e(k)}</span><span>${v.length} thuốc</span></summary>${v.map(card).join('')}</details>`).join('')}
function render(){const q=$('drugSearch').value.trim().toLowerCase(),g=new URLSearchParams(location.search).get('group');let a=D.drugs.slice();if(g&&G[g])a=a.filter(G[g][2]);if(q)a=a.filter(d=>[d.generic,d.brands,d.drug_class,...d.domains,d.prefer,d.trend,d.strengths,d.daily_dose,d.duration].join(' ').toLowerCase().includes(q));if(q){$('drugList').innerHTML=`<div class="section-heading"><h3>${a.length} thuốc phù hợp</h3><button id="clearSearch" class="ghost">Xóa tìm kiếm</button></div>${a.map(card).join('')||'<div class="empty-state"><h3>Chưa tìm thấy thuốc</h3></div>'}`;$('clearSearch')?.addEventListener('click',()=>{$('drugSearch').value='';render()});return}if(g&&G[g]){const x=G[g];$('drugList').innerHTML=`<section class="therapy-section"><div class="therapy-head"><div><span class="eyebrow">NHÓM ĐIỀU TRỊ</span><h2>${x[0]}</h2><p>${x[1]}</p></div></div>${classes(a)}</section>`;return}$('drugList').innerHTML=Object.entries(G).map(([id,x])=>{const a=D.drugs.filter(x[2]);return `<a class="therapy-section therapy-link" href="drugs.html?group=${id}"><div class="therapy-head"><div><span class="eyebrow">NHÓM ĐIỀU TRỊ</span><h2>${x[0]}</h2><p>${x[1]}</p></div><span class="therapy-count">${a.length}</span></div><div class="class-preview">${[...new Set(a.map(d=>d.drug_class))].slice(0,6).map(c=>`<span>${e(c)}</span>`).join('')}</div></a>`}).join('')}
async function init(){D=await LK.load('drugs');const ids=new Set((D.drugs||[]).map(x=>x.id));EXTRA.forEach(x=>{if(!ids.has(x.id))D.drugs.push(x)});$('principles').innerHTML='<ol class="principle-list">'+(D.principles||[]).map(x=>`<li>${e(x)}</li>`).join('')+'</ol>';$('disclaimer').textContent=D.disclaimer||'';const s=[];D.drugs.forEach(d=>{s.push(d.generic,d.drug_class);if(d.brands)s.push(...String(d.brands).split(/[,;/]/).map(x=>x.trim()).filter(Boolean))});$('drugSuggestions').innerHTML=[...new Set(s)].sort((a,b)=>a.localeCompare(b,'vi')).map(x=>`<option value="${e(x)}">`).join('');$('drugSearch').oninput=render;render()}init()})();