(()=>{
 const KEY='laokhoa.v8.quiz';
 let bank=[],meta={},guides={},sourceMap={},state={answers:{},cursor:0,orderSeed:0};
 try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x&&typeof x==='object'){state.answers=x.answers||{};state.cursor=Number.isInteger(x.cursor)?x.cursor:0;state.orderSeed=x.orderSeed||0}}catch(e){}
 const $=id=>document.getElementById(id),root=$('quizRoot'),cat=$('cat'),task=$('task'),mode=$('mode'),pos=$('pos'),idxBox=$('quizIndex'),seriesInfo=$('seriesInfo');
 const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
 function seeded(list){ if(!state.orderSeed) return list; let a=list.slice(),x=state.orderSeed>>>0; for(let i=a.length-1;i>0;i--){x=(1664525*x+1013904223)>>>0; const j=x%(i+1); [a[i],a[j]]=[a[j],a[i]];} return a; }
 function ids(){let a=bank.filter(q=>(cat.value==='all'||q.cat===cat.value)&&(task.value==='all'||q.task===task.value)); if(mode.value==='series')a=a.filter(q=>q.series_id); if(mode.value==='wrong')a=a.filter(q=>state.answers[q.id]!==undefined&&state.answers[q.id]!==q.ans); if(mode.value==='unanswered')a=a.filter(q=>state.answers[q.id]===undefined); return seeded(a);}
 function clamp(list){if(!list.length){state.cursor=0;return} if(!Number.isInteger(state.cursor)||state.cursor<0)state.cursor=0;if(state.cursor>=list.length)state.cursor=list.length-1;}
 function sourceHtml(q){if(!q.source_keys?.length)return ''; const links=q.source_keys.map(k=>{const s=sourceMap[k];return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>`:esc(k)});return `<div class="source-mini"><b>Nguồn:</b> ${links.join(' · ')}</div>`;}
 function renderIndex(list,currentId){idxBox.innerHTML=list.map((q,i)=>{const a=state.answers[q.id];let c='';if(a!==undefined)c=a===q.ans?'done':'wrong';if(q.id===currentId)c+=' current';return `<button class="${c}" data-jump="${i}" title="${esc(q.task)}">${i+1}</button>`}).join('');idxBox.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{state.cursor=Number(b.dataset.jump);save();render();scrollTo({top:0,behavior:'smooth'})});}
 function render(){const list=ids();clamp(list);$('bankMeta').textContent=`Ngân hàng ${meta.count||bank.length} câu · phiên bản ${meta.version||''} · đã làm ${Object.keys(state.answers).length} câu`;
  if(!list.length){root.innerHTML='<div class="qcard"><strong>Không có câu phù hợp bộ lọc.</strong></div>';pos.textContent='0/0';idxBox.innerHTML='';seriesInfo.innerHTML='';return;}
  const q=list[state.cursor],sel=state.answers[q.id]; const opts=q.opts.map((o,j)=>{let cls='qopt';if(sel!==undefined){if(j===q.ans)cls+=' correct';else if(j===sel)cls+=' wrong';}return `<button class="${cls}" data-opt="${j}" ${sel!==undefined?'disabled':''}><b>${'ABCD'[j]}.</b> ${esc(o)}</button>`}).join('');
  let ex='';if(sel!==undefined){ex='<div class="explain"><strong>Đáp án: '+ 'ABCD'[q.ans]+'</strong>'+q.expl.map((x,j)=>'<p><b>'+ 'ABCD'[j]+'.</b> '+esc(x)+'</p>').join('')+'<div class="key"><b>Điểm chốt:</b> '+esc(q.key)+'</div>'+sourceHtml(q)+'</div>';}
  const badges=`<span class="task-badge">${esc(q.task)}</span>${q.series_id?`<span class="series-badge">Ca ${esc(q.series_id)} · ${q.series_step}/3</span>`:''}${q.legacy?'<span class="task-badge">Câu cũ</span>':''}`;
  root.innerHTML=`<article class="qcard"><div>${badges}</div><div class="qnum">${esc(q.cat)} · ${esc(q.id)}</div><div class="qstem">${esc(q.stem)}</div><div class="qopts">${opts}</div>${ex}</article>`;
  seriesInfo.innerHTML=q.series_id?`<div class="exam-banner"><b>${esc(q.series_title||'Ca đa bệnh lý')}</b> · bước ${q.series_step}/3. Câu kế tiếp tiếp tục cùng bệnh nhân.</div>`:'';
  pos.textContent=(state.cursor+1)+'/'+list.length;root.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{state.answers[q.id]=Number(b.dataset.opt);save();render();});$('prev').disabled=state.cursor<=0;$('next').disabled=state.cursor>=list.length-1;renderIndex(list,q.id);
 }
 async function load(){try{const [qr,gr]=await Promise.all([fetch('data/questions.json?t='+Date.now(),{cache:'no-store'}),fetch('data/guidelines.json?t='+Date.now(),{cache:'no-store'})]);const qj=await qr.json();guides=await gr.json();bank=qj.questions||[];meta=qj;sourceMap=Object.fromEntries((guides.sources||[]).map(s=>[s.key,s]));[...new Set(bank.map(q=>q.cat))].sort((a,b)=>a.localeCompare(b,'vi')).forEach(c=>cat.insertAdjacentHTML('beforeend',`<option>${esc(c)}</option>`));render();}catch(e){root.innerHTML='<div class="qcard"><b>Không tải được ngân hàng câu hỏi.</b><p>Hãy mở app một lần khi có mạng để lưu dữ liệu offline.</p></div>';}}
 $('prev').onclick=()=>{if(state.cursor>0){state.cursor--;save();render();scrollTo({top:0,behavior:'smooth'})}};$('next').onclick=()=>{const l=ids();if(state.cursor<l.length-1){state.cursor++;save();render();scrollTo({top:0,behavior:'smooth'})}};[cat,task,mode].forEach(el=>el.onchange=()=>{state.cursor=0;render()});$('randomBtn').onclick=()=>{state.orderSeed=Date.now()&0xffffffff;state.cursor=0;save();render()};$('checkUpdate').onclick=async()=>{await load();alert('Đã kiểm tra và nạp lại dữ liệu mới nhất từ GitHub Pages.');};$('resetQuiz').onclick=()=>{if(confirm('Chỉ xóa đáp án MCQ? Bài học không bị ảnh hưởng.')){state={answers:{},cursor:0,orderSeed:0};save();render();}};load();
})();
